name: 'Notify on Commit Comment'
description: 'Sends notifications when a commit receives a comment'
inputs:
  slack_webhook_url:
    description: 'Slack Incoming Webhook URL'
    required: false
  discord_webhook_url:
    description: 'Discord Incoming Webhook URL'
    required: false
  telegram_bot_token:
    description: 'Telegram Bot Token'
    required: false
  telegram_chat_id:
    description: 'Telegram Chat ID'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
