name: 'Notify on Push Action'
description: 'Sends a Slack message when a git push occurs'
author: 'developjik'

inputs:
  slack_webhook_url:
    description: 'Slack Incoming Webhook URL'
    required: true

runs:
  using: 'node12'
  main: 'index.js'
